version: "3"

tasks:
  run:
    desc: "Run SSO server"
    cmds:
      - go run cmd/server/main.go -config config/local.yaml
  migrate:
    desc: "Run database migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/service.db --migrations-path=./migrations
